---
title: "Integrate ICS CD4 Magnitudes (truncated) and RNASeq data"
author: "Carl Murie and Raphael Gottardo"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
   BiocStyle::html_document:
    theme: lumen
    toc: true
    toc_float: true
    number_sections: true
---

```{r overall-knitr-options, echo=FALSE, results='hide'}
library(knitr)
opts_chunk$set(cache=FALSE, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, results='asis')
```

```{r packages}
library(RNASeqUtilities)
library(Biobase)
library(limma)
library(magrittr)
library(here)
library(data.table)
library(survival)   ## clogit
library(GSEABase)
library(tidyverse)
library(gridExtra)
library(DT)

source(here("code", "mal_utilities.R"))
```

```{r load-data}
library(mal067data)
data(mal067_eset)
```


```{r gsea}
min_gene_set <- 5

## set up GSEA analysis
btm_gtm <- getGmt(here("data/BTM_for_GSEA_20131008.gmt"))
btm_ind <- ids2indices(geneIds(btm_gtm), rownames(mal067_eset))
btm_ind <- btm_ind[sapply(btm_ind, length) > min_gene_set]
```


```{r getmorevars}
pfs <- readRDS(here("data/PRIMARY_CD4_MAGNITUDE.rds"))
stim <- "dmso"
```

```{r format}

## prune rnaseq eset to contain only same stimulations and sids
var_sids <- unique(pfs$PTID)

pData(mal067_eset) %>%
  filter(stimulation==stim) %>%
  filter(sid %in% var_sids) %$%
  col_id ->
  overlap

prune_meta <- mal067_voom[,overlap]
prune_meta$targets <- prune_meta$targets[,c("col_id", "case", "vaccine", "sid", "visit", "stimulation", "plate", "malaria_status")]

## filter ics data to reduce size
pfs %>%
  dplyr::rename(sid=PTID,
                visit=VISITNO) %>%
  select(c(sid, visit, difference_trunc)) %>%
   dplyr::inner_join(prune_meta$targets, by=c("sid", "visit"))->
  data

pfs_set <- prune_meta[,data$col_id]
pfs_set$targets <- data

if(sum(colnames(pfs_set) != pfs_set$targets$col_id) > 0) {
  stop("GSEA join is screwed up")
}

fdr_cut <- 0.2
coef <- "difference_trunc"
form <- "~plate+difference_trunc"
```

 
##Sample size  
  
```{r samples}
pfs_set$targets %>%
  countSampleSizes("visit", c("vaccine", "malaria_status", "stimulation")) %>%
  headerKable(labels=c("vaccine", "malaria", "stimulation"),
              levels=c(2,2,4))
```

#GSEA analysis of CD4 magnitudes {.tabset .tabset-fade .tabset-pills}

##M0

```{r m0} 

voom_m0 <- pfs_set[,pfs_set$targets$visit=="M0"]

## run camera
des <- model.matrix(formula(form), voom_m0$targets)
cam <- as_tibble(camera(voom_m0, btm_ind, design=des,
                              contrast=coef),
                       rownames="geneset")
 cam %>%
    mutate(PValue=signif(PValue, 3)) %>%
    mutate(FDR=signif(FDR, 3)) %>%
   filter(FDR <= fdr_cut) %>%
   datatable()
 
 summ <- sum(cam$FDR <= fdr_cut)
```
  
##M3

```{r m3} 

voom_m3 <- pfs_set[,pfs_set$targets$visit=="M3"]

## run camera
des <- model.matrix(formula(form), voom_m3$targets)
cam <- as_tibble(camera(voom_m3, btm_ind, design=des,
                              contrast=coef),
                       rownames="geneset")
 cam %>%
    mutate(PValue=signif(PValue, 3)) %>%
    mutate(FDR=signif(FDR, 3)) %>%
   filter(FDR <= fdr_cut) %>%
   datatable()
 
 summ <- c(summ, sum(cam$FDR <= fdr_cut))
```
  
#Summary
  
```{r summ}

outie <- data.frame(number=summ)
rownames(outie) <- c("M0", "M3")
headerKable(outie, title="number of significant gsea sets")
```


