---
title: "GSEA main effects: stimulation vs disease"
subtitle: "DMSO: M0"
author: "Carl Murie and Raphael Gottardo"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
   BiocStyle::html_document:
    theme: lumen
    toc: true
    toc_float: true
    number_sections: true
---

```{r overall-knitr-options, echo=FALSE, results='hide'}
library(knitr)
opts_chunk$set(cache=FALSE, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, results='asis')
```


```{r parameters}
## test main effects of vaccine and disease by stimulation

stim="dmso"
time="M0"
```


```{r load-packages}
library(RNASeqUtilities)
library(Biobase)
library(GSEABase)
library(DT)
library(limma)
library(tidyverse)
library(magrittr)
library(here)
library(readr)

source(here("code", "mal_utilities.R"))
```

```{r load-data}
library(mal067data)
data(mal067_eset)
meta_dt <- as.tibble(pData(mal067_eset))
```


```{r set-parameters}
SHOW_SAMPLE_SIZE <- TRUE

## parameters set by parent: stim, time
stim="dmso"
time="M0"

fdr_cut <- 0.2
p_cut <- 0.01
min_gene_set <- 5
form_interact_vac <- "~plate + total_reads + age_weeks + vaccine"
form_interact_dis <- "~plate + total_reads + age_weeks + case"

## store number of significant gene-sets for each comparison
summary_tab <- NULL

## if time is M0 set conditional to FALSE as there are no young subjects in M0
is_m0 <- time != "M0"
```

```{r genesets}
## set up GSEA analysis
btm_gtm <- getGmt(here("data/BTM_for_GSEA_20131008.gmt"))
btm_ind <- ids2indices(geneIds(btm_gtm), rownames(mal067_eset))
btm_ind <- btm_ind[sapply(btm_ind, length) > min_gene_set]
```

# GSEA `r toupper(stim)`: disease main effects

**disease linear model:** `r form_interact_dis`  
**disease filtering   :** `r time`, case/control, rtss 

```{r disease_data}
## disease: select subset of expressionSet
meta_dt %>% 
  filter(stimulation == stim) %>% 
  filter(visit == time) %>%
  filter(case != "neither") %>%
  filter(vaccine == "rtss") %$%
  col_id ->
  sample_vac

## generate subset data and drop extra stimulation/case levels
mal_dis <- mal067_eset[, sample_vac] 
mal_dis$stimulation <- fct_drop(mal_dis$stimulation)
mal_dis$case <- fct_drop(mal_dis$case)

```

##old age group {.tabset .tabset-fade .tabset-pills}

```{r sample_size, eval=SHOW_SAMPLE_SIZE}

## get sample sizes
countSampleSizes(pData(mal_dis), "stimulation", 
                 c("vaccine", "case", "age")) %>%
headerKable(labels=c("vaccine", "case", "age"), levels=c(2,2,2), 
            title="disease sample size")

```
  
###disease  

```{r dis_analysis, results="asis"}

################## disease analysis ############################

cam_dis <- runGSEA(mal_dis, 
                   form_interact_dis,
                   coef="casecase")
summary_tab <-  sum(cam_dis$FDR <= fdr_cut)
```

###table

```{r table}

## reformat and recalculate scores
cam_dis %>%
  filter(FDR <= fdr_cut | FDR <= fdr_cut) %>%
  filter(!grepl("TBA", geneset)) %>%
  ##filter(grepl("monocyte", geneset)) %>%
  mutate(PValue=signif(PValue, 3)) %>%
  mutate(FDR=signif(FDR,3)) %>%
  dplyr::select(-c(NGenes)) %>%
  headerKable() %>%
  row_spec(c(1,4,31), background = "yellow")

if(FALSE) {
  cam_dis %>%
  filter(FDR <= fdr_cut | FDR <= fdr_cut) %>%
  filter(!grepl("TBA", geneset)) %>%
  filter(grepl("monocyte", geneset)) %>%
  mutate(PValue=signif(PValue, 3)) %>%
  mutate(FDR=signif(FDR,3)) %>%
  dplyr::select(-c(NGenes)) %>%
  headerKable()
}
```


#Summary  
  
`r summary_tab` significant gene sets
